#ifndef TOMATKERNEL_PCI_DEVICE_SPEC_H
#define TOMATKERNEL_PCI_DEVICE_SPEC_H

#define PCI_DEVICE_REG_BASE_ADDRESS_REGISTERS       0x10
#define PCI_DEVICE_REG_CARDBUS_CIS_POINTER          0x28
#define PCI_DEVICE_REG_SUBSYSTEM_VENDOR_ID          0x2C
#define PCI_DEVICE_REG_SYSTEM_ID                    0x2E
#define PCI_DEVICE_REG_EXPANSION_ROM_BASE_ADDRESS   0x30
#define PCI_DEVICE_REG_MIN_GNT                      0x3E
#define PCI_DEVICE_REG_MAX_LAT                      0x3F

#endif //TOMATKERNEL_PCI_DEVICE_SPEC_H
